### ISSUE TITLE
app displays nothing

### ISSUE THREAD

**Issue by ajschumacher** [editdata/app.editdata.org#77]
### Expected behavior

When I go to http://app.editdata.org/edit/new, I see some sort of interface.

### Actual behavior

I see a white screen.

### Steps to reproduce

Go to http://app.editdata.org/edit/new.

It did work for me once, but after I had added two columns and a row it stopped responding and returning to http://app.editdata.org/edit/new doesn't display anything now.

**Comment by sethvincent** [comment]
Oh no, that is awful. I'll try and reproduce it. If you could copy/paste or get a screenshot of any error output from the js console that would be helpful.

**Comment by sethvincent** [comment]
OK, I think this happens when:

- I go to app.editdata.org, click new empty dataset
- make some changes at the `/edit/new` url
- go back to `/`
- click new empty dataset again

It probably happens anytime a user is editing a dataset, then goes back to `/`, then tries to create a new empty dataset.

It looks like it is the [data-form](http://github.com/editdata/data-form) module that is throwing the error because `options.row` is undefined.

**Comment by ajschumacher** [comment]
At least it's replicable! :smile:

**Comment by sethvincent** [comment]
:grimacing: 

To get the app back in a working condition, you can delete the `editdata-production` localstorage object in the developer tools, then log in again.

Working on an actual fix, though.

**Comment by sethvincent** [comment]
This should now be fixed 🔧
